dist: trusty
sudo: required

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  artifacts:
    # ...
    paths:
      - $(git ls-files -o | grep travis_artifacts | tr "\n" ":")

language: php

php:
  - 7.3

services:
  - docker

before_install:
  # Composer Configurations.
  - export COMPOSER_MEMORY_LIMIT=-1 # Set php memory limit to -1 so composer update will not fail
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1 # To enforce throwing an error and stopping package installation/update immediately
  - phpenv config-rm xdebug.ini

  # Travis self-updates it's PHP and Composer dependencies every 30-60 days, so it automatically updates to version 2
  - composer install --prefer-dist --no-interaction
  # Install docker and our docker containers.
  - sh scripts/social/ci/install-docker.sh
  - docker-compose -f docker-compose-ci.yml up -d

script:
  - docker exec -i social_ci_web bash /var/www/scripts/social/install/install_script.sh
#  - docker exec -i social_ci_web_scripts sh /var/www/scripts/social/unit-tests.sh
  - docker exec -i social_ci_web_scripts /var/www/scripts/social/run-tests.sh
  - docker exec -it social_ci_behat sh /var/www/scripts/social/behatstability.sh stability-1
