services:
  blackfire:
    image: blackfire/blackfire
    environment:
        # Exposes the host BLACKFIRE_SERVER_ID and BLACKFIRE_SERVER_TOKEN environment variables.
        # Find the values for these on https://blackfire.io/docs/integrations/docker while logged in.
        # For ease of use on multiple project copy those export statements to ~/.bash_profile.
        BLACKFIRE_SERVER_ID
        BLACKFIRE_SERVER_TOKEN
    ports:
      - "8307"
    container_name: "${PROJECT_NAME}_blackfire"

networks:
  # Default will connect all containers to the specified network.
  default:
    # Network name.
    name: nginx
    # Connects to an existing network.
    external: true
