# See: https://docs.docker.com/compose/compose-file/
# See: https://github.com/compose-spec/compose-spec/blob/master/spec.md
services:
  web:
    image: goalgorilla/open_social_docker:dev
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - db
      - mailcatcher
      - redis
      - solr
    environment:
      - DRUPAL_SETTINGS=development
    container_name: "${PROJECT_NAME}_web"
    labels:
      - "traefik.http.routers.web.rule=Host(`${PROJECT_BASE_URL}`)"

  db:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    container_name: "${PROJECT_NAME}_db"
    command: mysqld --max_allowed_packet=16M

  mailcatcher:
    image: schickling/mailcatcher
    container_name: "${PROJECT_NAME}_mailcatcher"
    labels:
      - "traefik.http.services.mailcatcher.loadbalancer.server.port=1080"
      - "traefik.http.routers.mailcatcher.rule=Host(`mailcatcher.${PROJECT_BASE_URL}`)"

  selenium:
    image: selenium/standalone-firefox-debug:2.48.2
    volumes:
      - ./html/profiles/contrib/social/tests/behat/features/files/:/files:delegated
    depends_on:
      - web
    ports:
      - "4444"
      - "5900"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    container_name: "${PROJECT_NAME}_selenium"

  behat:
    image: goalgorilla/open_social_docker:dev
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - web
      - db
      - selenium
    environment:
      - DRUPAL_SETTINGS=development
    container_name: "${PROJECT_NAME}_behat"

  cron:
    image: goalgorilla/open_social_docker:cron
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - db
      - mailcatcher
    environment:
      - DRUPAL_SETTINGS=development
    container_name: "${PROJECT_NAME}_cron"


  solr:
    image: solr:8.11
    hostname: solr
    volumes:
      - os_solr_data:/opt/solr/server/solr/mycores
      - ./docker/solr/8.x/drupal/:/solr-conf/conf:cached
    environment:
      - SOLR_SOLR_MEM_SIZE=512m
      - PARTIAL_SEARCH_ENABLED=false
    entrypoint:
      - solr-precreate
      - drupal
      - /solr-conf
    container_name: "${PROJECT_NAME}_solr"
    labels:
      - "traefik.http.services.solr.loadbalancer.server.port=8983"
      - "traefik.http.routers.solr.rule=Host(`solr.${PROJECT_BASE_URL}`)"

  redis:
    image: redis:latest
    container_name: "${PROJECT_NAME}_redis"

  reverse-proxy:
    image: traefik:v2.8
    container_name: "${PROJECT_NAME}_traefik"
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "${PROJECT_PORT}:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data:
  os_solr_data:
