# See: https://docs.docker.com/compose/compose-file/
# See: https://github.com/compose-spec/compose-spec/blob/master/spec.md
services:
  web:
    image: goalgorilla/open_social_docker:dev
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - db
      - mailcatcher
      - redis
      - solr
    environment:
      - DRUPAL_SETTINGS=development
    container_name: social_web
    labels:
      - "traefik.http.routers.web.rule=Host(`social.local`)"

  db:
    image: mariadb:10.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=social
    volumes:
      - db_data:/var/lib/mysql
    container_name: social_db
    command: mysqld --max_allowed_packet=16M

  mailcatcher:
    image: schickling/mailcatcher
    container_name: social_mailcatcher
    labels:
      - "traefik.http.services.mailcatcher.loadbalancer.server.port=1080"
      - "traefik.http.routers.mailcatcher.rule=Host(`mailcatcher.social.local`)"

  selenium:
    image: selenium/standalone-firefox-debug:2.48.2
    volumes:
      - ./html/profiles/contrib/social/tests/behat/features/files/:/files:delegated
    depends_on:
      - web
    ports:
      - "4444"
      - "5900"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    container_name: social_selenium

  behat:
    image: goalgorilla/open_social_docker:dev
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - web
      - db
      - selenium
    environment:
      - DRUPAL_SETTINGS=development
    container_name: social_behat

  cron:
    image: goalgorilla/open_social_docker:cron
    volumes:
      - ./:/var/www:delegated
    depends_on:
      - db
      - mailcatcher
    environment:
      - DRUPAL_SETTINGS=development
    container_name: social_cron

  solr:
    image: solr:8.11
    hostname: solr
    volumes:
      - os_solr_data:/opt/solr/server/solr/mycores
      - ./docker/solr/8.x/drupal/:/solr-conf/conf:cached
    environment:
      - SOLR_SOLR_MEM_SIZE=512m
      - PARTIAL_SEARCH_ENABLED=false
    entrypoint:
      - solr-precreate
      - drupal
      - /solr-conf
    container_name: social_solr
    labels:
      - "traefik.http.services.solr.loadbalancer.server.port=8983"
      - "traefik.http.routers.solr.rule=Host(`solr.social.local`)"

  redis:
    image: redis:latest

  reverse-proxy:
    image: traefik:v2.8
    container_name: social__traefik
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data:
  os_solr_data:
